# Generated by Django 4.1.2 on 2022-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('tonnage', models.TextField(max_length=100, verbose_name='Деякий текст')),
                ('am_of_passengers', models.IntegerField(blank=True, null=True, verbose_name='Деякі числа')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
